# Generated by Django 2.1.3 on 2018-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favor_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
