# Generated by Django 2.1.3 on 2018-11-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favor_exchange', '0002_auto_20181115_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='amount',
            field=models.IntegerField(default=10),
        ),
    ]
